# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='authorq',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_dateq',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='published_dateq',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='textq',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titleq',
        ),
    ]
